MONGO_HOST = "localhost"
MONGO_PORT = 27017
MONGO_DB_NAME = "SD2026_projet"

COLLECTION_PREFIX = "G_AP"

COLLECTION_SOURCES = f"{COLLECTION_PREFIX}_sources"
COLLECTION_ARTICLES = f"{COLLECTION_PREFIX}_articles"
COLLECTION_CONSULTATIONS = f"{COLLECTION_PREFIX}_consultations"
